package com.orozco.gesterin.vista;

/**
 *
 * @author CRISTIAN MANUEL OROZCO
 * @legajo VINF014304
 * @fecha 17 sep. 2024
 * @description Sistema GESTERIN
 */
public class JFPrincipal extends javax.swing.JFrame {

    public JFPrincipal() {
        initComponents();
          this.setLocationRelativeTo(null);
        //iniciar en modo maximizado
        this.setExtendedState(JFPrincipal.MAXIMIZED_BOTH);
    }

    public void ingresarAUnMnu() {
        this.jMnuInicio.setEnabled(false);
        this.jMnuCliente.setEnabled(false);
    }

    public void salirAlMnuPpal() {
        this.jMnuInicio.setEnabled(true);
        this.jMnuCliente.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuInicio = new javax.swing.JMenu();
        jMnuExit = new javax.swing.JMenuItem();
        jMnuUsuarios = new javax.swing.JMenu();
        jMniGestionCliente1 = new javax.swing.JMenuItem();
        jMnuCliente = new javax.swing.JMenu();
        jMniGestionCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        jMnuInicio.setText("Inicio");

        jMnuExit.setText("Salir");
        jMnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuExitActionPerformed(evt);
            }
        });
        jMnuInicio.add(jMnuExit);

        jMenuBar1.add(jMnuInicio);

        jMnuUsuarios.setText("Usuarios");

        jMniGestionCliente1.setText("Gestión");
        jMniGestionCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniGestionCliente1ActionPerformed(evt);
            }
        });
        jMnuUsuarios.add(jMniGestionCliente1);

        jMenuBar1.add(jMnuUsuarios);

        jMnuCliente.setText("Clientes");

        jMniGestionCliente.setText("Gestión");
        jMniGestionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniGestionClienteActionPerformed(evt);
            }
        });
        jMnuCliente.add(jMniGestionCliente);

        jMenuBar1.add(jMnuCliente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMniGestionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniGestionClienteActionPerformed
        iFGestionClientes gestionPacientes = new iFGestionClientes(this.jDesktop, this);
        UtilGUI.openInternalFrame(this.jDesktop, gestionPacientes);
        this.ingresarAUnMnu();
    }//GEN-LAST:event_jMniGestionClienteActionPerformed

    private void jMnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMnuExitActionPerformed

    private void jMniGestionCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniGestionCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMniGestionCliente1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMniGestionCliente;
    private javax.swing.JMenuItem jMniGestionCliente1;
    private javax.swing.JMenu jMnuCliente;
    private javax.swing.JMenuItem jMnuExit;
    private javax.swing.JMenu jMnuInicio;
    private javax.swing.JMenu jMnuUsuarios;
    // End of variables declaration//GEN-END:variables
}
