package com.orozco.gesterin.gui;

/**
 *
 * @author CRISTIAN MANUEL OROZCO
 * @legajo VINF014304
 * @fecha 17 sep. 2024
 * @description Sistema GESTERIN
 */
public class JFPrincipal extends javax.swing.JFrame {

    iFGestionPacientes iFGestionPacientes;

    public JFPrincipal() {
        initComponents();
          this.setLocationRelativeTo(null);
        //iniciar en modo maximizado
        this.setExtendedState(JFPrincipal.MAXIMIZED_BOTH);
    }

    public void ingresarAUnMnu() {
        this.jMnuInicio.setEnabled(false);
        this.jMnuGestionPaciente.setEnabled(false);
    }

    public void salirAlMnuPpal() {
        this.jMnuInicio.setEnabled(true);
        this.jMnuGestionPaciente.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuInicio = new javax.swing.JMenu();
        jMnuExit = new javax.swing.JMenuItem();
        jMnuGestionPaciente = new javax.swing.JMenu();
        jMniGestionPaciente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        jMnuInicio.setText("Inicio");

        jMnuExit.setText("Salir");
        jMnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuExitActionPerformed(evt);
            }
        });
        jMnuInicio.add(jMnuExit);

        jMenuBar1.add(jMnuInicio);

        jMnuGestionPaciente.setText("Gestion Pacientes");

        jMniGestionPaciente.setText("Gestión");
        jMniGestionPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniGestionPacienteActionPerformed(evt);
            }
        });
        jMnuGestionPaciente.add(jMniGestionPaciente);

        jMenuBar1.add(jMnuGestionPaciente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMniGestionPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniGestionPacienteActionPerformed

        iFGestionPacientes gestionPacientes = new iFGestionPacientes(this.jDesktop, this);
        UtilGUI.openInternalFrame(this.jDesktop, gestionPacientes);
        this.ingresarAUnMnu();
        //Prueba de cambios
//        iFGestionPacientes gestionPacientes = new iFGestionPacientes(this.jDesktop, this);
//        if (UtilGUI.openInternalFrame(gestionPacientes, this.jDesktop)) {
//            this.iFGestionPacientes = gestionPacientes;
//            UtilGUI.crearVentanaInterna(this.jDesktop, this.iFGestionPacientes);
//            this.ingresarAUnMnu();
//        } else {
//            this.iFGestionPacientes.moveToFront();
//        }
//        this.jDesktop.add(gestionPacientes);
//        gestionPacientes.show();
    }//GEN-LAST:event_jMniGestionPacienteActionPerformed

    private void jMnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMnuExitActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Principal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMniGestionPaciente;
    private javax.swing.JMenuItem jMnuExit;
    private javax.swing.JMenu jMnuGestionPaciente;
    private javax.swing.JMenu jMnuInicio;
    // End of variables declaration//GEN-END:variables
}
